services:
  postgres:
    image: postgres:17
    container_name: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - app-network
    env_file:
      .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 0.5s
      retries: 10

  django:
    restart: always
    build: ./django
    container_name: django
    volumes:
      - ./django/app:/app/
    networks:
      - app-network
    env_file:
      .env
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    restart: always
    build: ./nginx
    container_name: nginx
    volumes: 
      - ./django/app/transcendence/static:/static
    networks:
      - app-network
    env_file:
      .env
    ports:
      - 8000:443
    depends_on:
      - django

  redis:
    image: redis:7.4.1
    container_name: redis
    volumes:
      - ./data/redis:/data
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
