services:
  postgres:
    image: postgres:17
    container_name: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - app-network
    env_file:
      .env
  django:
    build: ./django
    container_name: django
    volumes:
      - ./django/app:/app/
    networks:
      - app-network
    env_file:
      .env

networks:
  app-network:
    driver: bridge
