# global:
#   smtp_smarthost: 'smtp.gmail.com:587'
#   smtp_from: "transcendence2442@gmail.com"
#   smtp_auth_username: "transcendence2442@gmail.com"
#   smtp_auth_password: "lxrk-qmyu-tssa-hqmn"
#   smtp_require_tls: true

# route:
#   group_by: ['alertname', 'job']
#   group_wait: 30s
#   group_interval: 5m
#   repeat_interval: 1h
#   receiver: 'email-alerts'

# receivers:
# - name: 'email-alerts'
#   email_configs:
#   - to: "transcendence2442@gmail.com"
#     send_resolved: true

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email-alerts'

receivers:
- name: 'email-alerts'
  email_configs:
  - to: '${EMAIL_HOST_USER}'
    from: '${EMAIL_HOST_USER}'
    smarthost: 'smtp.gmail.com:587'
    auth_username: '${EMAIL_HOST_USER}'
    auth_password: '${EMAIL_HOST_PASSWORD}'
    auth_identity: '${EMAIL_HOST_USER}'
    send_resolved: true
    headers:
      subject: '[ALERT] {{ .Status | toUpper }} - {{ .GroupLabels.alertname }}'
    html: |
      <html>
      <body>
      <h2>{{ .Status | toUpper }} - {{ .GroupLabels.alertname }}</h2>
      <p><strong>Severity:</strong> {{ .CommonLabels.severity }}</p>
      <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
      <h3>Affected Services:</h3>
      <ul>
      {{ range .Alerts }}
        <li>
          <strong>Job:</strong> {{ .Labels.job }}<br>
          <strong>Instance:</strong> {{ .Labels.instance }}
        </li>
      {{ end }}
      </ul>
      </body>
      </html>




# global:
#   smtp_smarthost: 'smtp.gmail.com:587'  # Replace with your SMTP server
#   smtp_from: 'your-email@gmail.com'    # Replace with your email address
#   smtp_auth_username: 'your-email@gmail.com'
#   smtp_auth_password: 'your-email-password'
#   smtp_require_tls: true

# route:
#   receiver: 'email-alert'

# receivers:
#   - name: 'email-alert'
#     email_configs:
#       - to: 'recipient-email@gmail.com'  # Replace with the recipient's email address
#         send_resolved: true             # Set to true if you want notifications when an alert is resolved


