global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alertrules.yml

scrape_configs:
  - job_name: 'django'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['django:8000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
